global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "decidr-go"
    static_configs:
      - targets: ['172.17.0.1:8080']
  
  - job_name: 'otelcol'
    static_configs:
      - targets: ['otelcol:8888']